apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: component-engine

build:
  local:
    push: true
  artifacts:
    - image: ghcr.io/ardo314/component-engine-backend
      context: .
      docker:
        dockerfile: engine/backend/Dockerfile

    - image: ghcr.io/ardo314/component-engine-editor
      context: .
      docker:
        dockerfile: engine/editor/Dockerfile

    - image: ghcr.io/ardo314/component-engine-in-memory-worker
      context: .
      docker:
        dockerfile: workers/in-memory/Dockerfile

    - image: ghcr.io/ardo314/component-engine-nova-worker
      context: .
      docker:
        dockerfile: workers/nova/Dockerfile

    - image: ghcr.io/ardo314/component-engine-nova
      context: .
      requires:
        - image: ghcr.io/ardo314/component-engine-backend
          alias: BACKEND_IMAGE
        - image: ghcr.io/ardo314/component-engine-editor
          alias: EDITOR_IMAGE
        - image: ghcr.io/ardo314/component-engine-in-memory-worker
          alias: WORKER_IMAGE_0
        - image: ghcr.io/ardo314/component-engine-nova-worker
          alias: WORKER_IMAGE_1
      docker:
        dockerfile: deployments/nova/Dockerfile
