apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: component-engine

build:
  local:
    push: true
  artifacts:
    - image: ghcr.io/ardo314/component-engine-backend
      context: .
      docker:
        dockerfile: engine/Dockerfile

    - image: ghcr.io/ardo314/component-engine-editor
      context: .
      docker:
        dockerfile: editor/Dockerfile

    - image: ghcr.io/ardo314/component-engine-nova-provider
      context: .
      docker:
        dockerfile: providers/nova/Dockerfile

    - image: ghcr.io/ardo314/component-engine-nova
      context: .
      requires:
        - image: ghcr.io/ardo314/component-engine-backend
          alias: BACKEND_IMAGE
        - image: ghcr.io/ardo314/component-engine-editor
          alias: EDITOR_IMAGE
        - image: ghcr.io/ardo314/component-engine-nova-provider
          alias: PROVIDER_IMAGE_0
      docker:
        dockerfile: deployments/nova/Dockerfile
