using Engine.Core;
using NATS.Client.Core;

namespace Engine.Client;

/// <summary>
/// Client-side proxy for a single entity.
/// Component operations are forwarded to the backend over NATS request-reply.
/// </summary>
public sealed class Entity
{
    private readonly INatsConnection _nats;

    public EntityId Id { get; }

    /// <summary>
    /// The NATS connection used by this entity for component proxies.
    /// </summary>
    public INatsConnection Nats => _nats;

    public Entity(EntityId id, INatsConnection nats)
    {
        Id = id;
        _nats = nats;
    }

    /// <summary>
    /// Registers a component on this entity via the backend.
    /// The marker struct <typeparamref name="TComponent"/> must carry <c>[Has&lt;...&gt;]</c>
    /// attributes indicating which component interfaces it provides.
    /// </summary>
    public async Task AddComponentAsync<TComponent>(CancellationToken ct = default)
        where TComponent : struct
    {
        var payload = $"{Id.Value}:{typeof(TComponent).Name}";
        var reply = await _nats.RequestAsync<string, string>(
            "entity.add-component",
            payload,
            cancellationToken: ct
        );

        if (reply.Data is not "ok")
            throw new InvalidOperationException(
                $"Failed to add component {typeof(TComponent).Name} to entity {Id}: {reply.Data}"
            );
    }

    /// <summary>
    /// Removes a component from this entity via the backend.
    /// </summary>
    public async Task RemoveComponentAsync<TComponent>(CancellationToken ct = default)
        where TComponent : struct
    {
        var payload = $"{Id.Value}:{typeof(TComponent).Name}";
        var reply = await _nats.RequestAsync<string, string>(
            "entity.remove-component",
            payload,
            cancellationToken: ct
        );

        if (reply.Data is not "ok")
            throw new InvalidOperationException(
                $"Failed to remove component {typeof(TComponent).Name} from entity {Id}: {reply.Data}"
            );
    }

    /// <summary>
    /// Checks whether this entity has a given component via the backend.
    /// </summary>
    public async Task<bool> HasComponentAsync<TComponent>(CancellationToken ct = default)
        where TComponent : struct
    {
        var payload = $"{Id.Value}:{typeof(TComponent).Name}";
        var reply = await _nats.RequestAsync<string, string>(
            "entity.has-component",
            payload,
            cancellationToken: ct
        );

        return reply.Data is "true";
    }

    /// <summary>
    /// Lists all component names attached to this entity.
    /// </summary>
    public async Task<IReadOnlyList<string>> ListComponentsAsync(CancellationToken ct = default)
    {
        var reply = await _nats.RequestAsync<string, string>(
            "entity.list-components",
            Id.Value.ToString(),
            cancellationToken: ct
        );

        if (string.IsNullOrEmpty(reply.Data))
            return Array.Empty<string>();

        return reply.Data!.Split(',');
    }

    /// <summary>
    /// Returns a client-side proxy for the given component interface.
    /// The proxy type is resolved by convention: the interface name with the leading 'I' stripped
    /// and "Proxy" appended (e.g., <c>IPose</c> → <c>PoseProxy</c>), generated by Engine.Generators.
    /// Searches all loaded assemblies because proxy types are generated in module projects.
    /// </summary>
    public TComponent GetComponent<TComponent>()
        where TComponent : IComponent
    {
        var interfaceType = typeof(TComponent);
        var interfaceName = interfaceType.Name;
        var proxyName =
            interfaceName.Length > 1 && interfaceName[0] == 'I' && char.IsUpper(interfaceName[1])
                ? interfaceName.Substring(1) + "Proxy"
                : interfaceName + "Proxy";

        var qualifiedName = $"{interfaceType.Namespace}.{proxyName}";

        foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
        {
            var proxyType = assembly.GetType(qualifiedName);
            if (proxyType is not null && interfaceType.IsAssignableFrom(proxyType))
                return (TComponent)Activator.CreateInstance(proxyType, Id, _nats)!;
        }

        throw new InvalidOperationException(
            $"No generated proxy type '{proxyName}' found for component '{interfaceName}'. "
                + "Ensure Engine.Generators is referenced as an analyzer in the module project."
        );
    }
}
