using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Engine.Generators;

/// <summary>
/// Emits client proxy classes for <c>IBehaviour</c>-derived interfaces.
/// Each proxy method serializes its arguments with MessagePack, sends a NATS request,
/// and deserializes the response.
/// </summary>
internal static class ClientProxyEmitter
{
    public static void Emit(
        SourceProductionContext context,
        ImmutableArray<BehaviourInterfaceInfo> interfaces
    )
    {
        if (interfaces.IsDefaultOrEmpty)
            return;

        foreach (var iface in interfaces.Distinct())
        {
            var source = GenerateProxy(iface);
            context.AddSource($"{iface.ProxyClassName}.g.cs", source);
        }
    }

    private static string GenerateProxy(BehaviourInterfaceInfo iface)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using NATS.Client.Core;");
        sb.AppendLine("using MessagePack;");
        sb.AppendLine();

        var ns = iface.Namespace ?? "Engine.Generated.Client";
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// Generated client proxy for <see cref=\"{iface.InterfaceName}\"/>.");
        sb.AppendLine($"/// Sends NATS requests serialized with MessagePack.");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"public sealed class {iface.ProxyClassName} : {iface.FullyQualifiedName}");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly INatsConnection _connection;");
        sb.AppendLine("    private readonly MessagePackSerializerOptions _options;");
        sb.AppendLine();
        sb.AppendLine(
            $"    public {iface.ProxyClassName}(INatsConnection connection, MessagePackSerializerOptions? options = null)"
        );
        sb.AppendLine("    {");
        sb.AppendLine("        _connection = connection;");
        sb.AppendLine("        _options = options ?? MessagePackSerializerOptions.Standard;");
        sb.AppendLine("    }");

        foreach (var method in iface.Methods)
        {
            sb.AppendLine();
            EmitProxyMethod(sb, iface, method);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitProxyMethod(
        StringBuilder sb,
        BehaviourInterfaceInfo iface,
        MethodInfo method
    )
    {
        var subject = SubjectNaming.ForBehaviourMethod(iface.InterfaceName, method.Name);
        var nonCtParams = method.Parameters.Where(p => !p.IsCancellationToken).ToList();
        var ctParam = method.Parameters.FirstOrDefault(p => p.IsCancellationToken);
        var ctArg = ctParam != null ? ctParam.Name : "default";

        // Build parameter list
        var paramList = string.Join(", ", method.Parameters.Select(p => $"{p.Type} {p.Name}"));

        sb.AppendLine($"    public async {method.ReturnType} {method.Name}({paramList})");
        sb.AppendLine("    {");

        if (method.ReturnsVoidTask)
        {
            // Fire-and-forget publish
            if (nonCtParams.Count == 0)
            {
                sb.AppendLine(
                    $"        await _connection.PublishAsync(\"{subject}\", cancellationToken: {ctArg}).ConfigureAwait(false);"
                );
            }
            else if (nonCtParams.Count == 1)
            {
                var p = nonCtParams[0];
                sb.AppendLine(
                    $"        var payload = MessagePackSerializer.Serialize({p.Name}, _options);"
                );
                sb.AppendLine(
                    $"        await _connection.PublishAsync(\"{subject}\", payload, cancellationToken: {ctArg}).ConfigureAwait(false);"
                );
            }
            else
            {
                // Multiple params — wrap in a tuple serialization
                var tupleArgs = string.Join(", ", nonCtParams.Select(p => p.Name));
                var tupleTypes = string.Join(", ", nonCtParams.Select(p => p.Type));
                sb.AppendLine(
                    $"        var payload = MessagePackSerializer.Serialize<({tupleTypes})>(({tupleArgs}), _options);"
                );
                sb.AppendLine(
                    $"        await _connection.PublishAsync(\"{subject}\", payload, cancellationToken: {ctArg}).ConfigureAwait(false);"
                );
            }
        }
        else
        {
            // Request/reply
            // Extract inner type from Task<T>
            var innerType = ExtractTaskInnerType(method.ReturnType);

            if (nonCtParams.Count == 0)
            {
                sb.AppendLine(
                    $"        var reply = await _connection.RequestAsync<byte[], byte[]>(\"{subject}\", Array.Empty<byte>(), cancellationToken: {ctArg}).ConfigureAwait(false);"
                );
            }
            else if (nonCtParams.Count == 1)
            {
                var p = nonCtParams[0];
                sb.AppendLine(
                    $"        var payload = MessagePackSerializer.Serialize({p.Name}, _options);"
                );
                sb.AppendLine(
                    $"        var reply = await _connection.RequestAsync<byte[], byte[]>(\"{subject}\", payload, cancellationToken: {ctArg}).ConfigureAwait(false);"
                );
            }
            else
            {
                var tupleArgs = string.Join(", ", nonCtParams.Select(p => p.Name));
                var tupleTypes = string.Join(", ", nonCtParams.Select(p => p.Type));
                sb.AppendLine(
                    $"        var payload = MessagePackSerializer.Serialize<({tupleTypes})>(({tupleArgs}), _options);"
                );
                sb.AppendLine(
                    $"        var reply = await _connection.RequestAsync<byte[], byte[]>(\"{subject}\", payload, cancellationToken: {ctArg}).ConfigureAwait(false);"
                );
            }

            sb.AppendLine(
                $"        if (reply.Data is null) throw new InvalidOperationException(\"Received null response for {method.Name}\");"
            );
            sb.AppendLine(
                $"        return MessagePackSerializer.Deserialize<{innerType}>(reply.Data, _options);"
            );
        }

        sb.AppendLine("    }");
    }

    private static string ExtractTaskInnerType(string returnType)
    {
        // returnType looks like "global::System.Threading.Tasks.Task<SomeType>"
        var idx = returnType.IndexOf('<');
        if (idx < 0)
            return returnType;
        return returnType.Substring(idx + 1, returnType.Length - idx - 2);
    }
}
