using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Engine.Generators;

/// <summary>
/// Emits partial classes for <c>Component&lt;TContract&gt;</c> subclasses.
/// Each partial class adds:
/// <list type="bullet">
///   <item>The contract interface (e.g., <c>: IPose</c>)</item>
///   <item><c>Updated</c> event</item>
///   <item><c>RaiseUpdated</c> protected method</item>
/// </list>
/// </summary>
internal static class ComponentEmitter
{
    public static void Emit(
        SourceProductionContext context,
        ImmutableArray<ComponentImplInfo> implementations
    )
    {
        if (implementations.IsDefaultOrEmpty)
            return;

        foreach (var impl in implementations.Distinct())
        {
            var source = GeneratePartial(impl);
            context.AddSource($"{impl.ClassName}.g.cs", source);
        }
    }

    private static string GeneratePartial(ComponentImplInfo impl)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Engine.Core;");
        sb.AppendLine();

        if (impl.Namespace is not null)
        {
            sb.AppendLine($"namespace {impl.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"/// <summary>");
        sb.AppendLine(
            $"/// Generated partial class — adds the <see cref=\"{impl.ContractInterfaceName}\"/> interface"
        );
        sb.AppendLine($"/// and event infrastructure for <see cref=\"{impl.ClassName}\"/>.");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"public partial class {impl.ClassName} : {impl.FullyQualifiedContractName}");
        sb.AppendLine("{");

        // Events
        sb.AppendLine($"    /// <inheritdoc />");
        sb.AppendLine($"    public event Action<{impl.FullyQualifiedDataType}>? Updated;");
        sb.AppendLine();

        // RaiseUpdated
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine(
            $"    /// Call this from <see cref=\"SetAsync\"/> after a successful write to fire the"
        );
        sb.AppendLine($"    /// <see cref=\"Updated\"/> event.");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    protected void RaiseUpdated({impl.FullyQualifiedDataType} data)");
        sb.AppendLine("    {");
        sb.AppendLine("        Updated?.Invoke(data);");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        return sb.ToString();
    }
}
