using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Engine.Generators;

/// <summary>
/// Emits a composite MessagePack <c>IFormatterResolver</c> that registers all
/// <c>IComponent</c> types found in the compilation.
/// </summary>
internal static class MessagePackEmitter
{
    public static void Emit(
        SourceProductionContext context,
        ImmutableArray<ComponentInfo> components
    )
    {
        if (components.IsDefaultOrEmpty)
            return;

        var distinct = components.Distinct().ToList();
        var source = GenerateResolver(distinct);
        context.AddSource("EngineComponentResolver.g.cs", source);
    }

    private static string GenerateResolver(
        System.Collections.Generic.List<ComponentInfo> components
    )
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using MessagePack;");
        sb.AppendLine("using MessagePack.Formatters;");
        sb.AppendLine("using MessagePack.Resolvers;");
        sb.AppendLine();
        sb.AppendLine("namespace Engine.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Auto-generated composite resolver that includes all IComponent types.");
        sb.AppendLine(
            "/// Use <see cref=\"Options\"/> as the <see cref=\"MessagePackSerializerOptions\"/> for serialization."
        );
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class EngineComponentResolver");
        sb.AppendLine("{");

        // Emit a static list of known component types for runtime inspection
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// All IComponent types discovered in this assembly at compile time.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static IReadOnlyList<Type> ComponentTypes { get; } = new Type[]");
        sb.AppendLine("    {");
        foreach (var c in components)
        {
            sb.AppendLine($"        typeof({c.FullyQualifiedName}),");
        }
        sb.AppendLine("    };");
        sb.AppendLine();

        // Emit a pre-configured MessagePackSerializerOptions
        sb.AppendLine("    /// <summary>");
        sb.AppendLine(
            "    /// Pre-configured serializer options that include the standard resolver"
        );
        sb.AppendLine("    /// with support for all discovered component types.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static MessagePackSerializerOptions Options { get; } =");
        sb.AppendLine("        MessagePackSerializerOptions.Standard");
        sb.AppendLine("            .WithResolver(");
        sb.AppendLine("                CompositeResolver.Create(");
        sb.AppendLine("                    StandardResolver.Instance));");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
