using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Engine.Generators;

/// <summary>
/// Emits server dispatch stubs for concrete classes implementing <c>IBehaviour</c>-derived interfaces.
/// Each dispatcher subscribes to NATS subjects, deserializes requests, invokes the implementation,
/// and replies with the serialized result.
/// </summary>
internal static class ServerStubEmitter
{
    public static void Emit(
        SourceProductionContext context,
        ImmutableArray<BehaviourImplInfo> implementations
    )
    {
        if (implementations.IsDefaultOrEmpty)
            return;

        foreach (var impl in implementations.Distinct())
        {
            var source = GenerateDispatcher(impl);
            context.AddSource($"{impl.DispatcherClassName}.g.cs", source);
        }
    }

    private static string GenerateDispatcher(BehaviourImplInfo impl)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using NATS.Client.Core;");
        sb.AppendLine("using MessagePack;");
        sb.AppendLine();

        var ns = impl.Namespace ?? "Engine.Generated.Server";
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// Generated server dispatcher for <see cref=\"{impl.ClassName}\"/>.");
        sb.AppendLine($"/// Subscribes to NATS subjects and routes to the implementation.");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"public sealed class {impl.DispatcherClassName} : IAsyncDisposable");
        sb.AppendLine("{");
        sb.AppendLine($"    private readonly {impl.FullyQualifiedClassName} _implementation;");
        sb.AppendLine("    private readonly INatsConnection _connection;");
        sb.AppendLine("    private readonly MessagePackSerializerOptions _options;");
        sb.AppendLine(
            "    private readonly System.Collections.Generic.List<IAsyncDisposable> _subscriptions = new();"
        );
        sb.AppendLine("    private readonly CancellationTokenSource _cts = new();");
        sb.AppendLine();
        sb.AppendLine(
            $"    public {impl.DispatcherClassName}({impl.FullyQualifiedClassName} implementation, INatsConnection connection, MessagePackSerializerOptions? options = null)"
        );
        sb.AppendLine("    {");
        sb.AppendLine("        _implementation = implementation;");
        sb.AppendLine("        _connection = connection;");
        sb.AppendLine("        _options = options ?? MessagePackSerializerOptions.Standard;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Starts listening on NATS subjects for all behaviour methods.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public async Task StartAsync(CancellationToken ct = default)");
        sb.AppendLine("    {");

        foreach (var contract in impl.Contracts)
        {
            foreach (var method in contract.Methods)
            {
                var subject = SubjectNaming.ForBehaviourMethod(contract.InterfaceName, method.Name);
                var handlerName = $"Handle_{contract.InterfaceName}_{method.Name}";
                sb.AppendLine($"        _ = SubscribeAsync(\"{subject}\", {handlerName}, ct);");
            }
        }

        sb.AppendLine("    }");

        // Generate handler methods
        foreach (var contract in impl.Contracts)
        {
            foreach (var method in contract.Methods)
            {
                sb.AppendLine();
                EmitHandler(sb, contract, method);
            }
        }

        sb.AppendLine();
        sb.AppendLine(
            "    private async Task SubscribeAsync(string subject, Func<NatsMsg<byte[]>, Task> handler, CancellationToken ct)"
        );
        sb.AppendLine("    {");
        sb.AppendLine(
            "        var linkedCts = CancellationTokenSource.CreateLinkedTokenSource(ct, _cts.Token);"
        );
        sb.AppendLine(
            "        await foreach (var msg in _connection.SubscribeAsync<byte[]>(subject, cancellationToken: linkedCts.Token))"
        );
        sb.AppendLine("        {");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                await handler(msg).ConfigureAwait(false);");
        sb.AppendLine("            }");
        sb.AppendLine("            catch (Exception ex)");
        sb.AppendLine("            {");
        sb.AppendLine(
            "                Console.Error.WriteLine($\"Error handling {subject}: {ex}\");"
        );
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public async ValueTask DisposeAsync()");
        sb.AppendLine("    {");
        sb.AppendLine("        _cts.Cancel();");
        sb.AppendLine("        foreach (var sub in _subscriptions)");
        sb.AppendLine("        {");
        sb.AppendLine("            await sub.DisposeAsync().ConfigureAwait(false);");
        sb.AppendLine("        }");
        sb.AppendLine("        _cts.Dispose();");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitHandler(
        StringBuilder sb,
        BehaviourContractInfo contract,
        MethodInfo method
    )
    {
        var nonCtParams = method.Parameters.Where(p => !p.IsCancellationToken).ToList();
        var handlerName = $"Handle_{contract.InterfaceName}_{method.Name}";

        sb.AppendLine($"    private async Task {handlerName}(NatsMsg<byte[]> msg)");
        sb.AppendLine("    {");

        // Deserialize parameters
        if (nonCtParams.Count == 1)
        {
            var p = nonCtParams[0];
            sb.AppendLine(
                $"        var {p.Name} = msg.Data is null ? default({p.Type})! : MessagePackSerializer.Deserialize<{p.Type}>(msg.Data, _options);"
            );
        }
        else if (nonCtParams.Count > 1)
        {
            var tupleTypes = string.Join(", ", nonCtParams.Select(p => p.Type));
            sb.AppendLine(
                $"        var args = msg.Data is null ? default(({tupleTypes})) : MessagePackSerializer.Deserialize<({tupleTypes})>(msg.Data, _options);"
            );
            for (int i = 0; i < nonCtParams.Count; i++)
            {
                sb.AppendLine($"        var {nonCtParams[i].Name} = args.Item{i + 1};");
            }
        }

        // Build call arguments
        var callArgs = string.Join(
            ", ",
            method.Parameters.Select(p => p.IsCancellationToken ? "CancellationToken.None" : p.Name)
        );

        if (method.ReturnsVoidTask)
        {
            sb.AppendLine(
                $"        await _implementation.{method.Name}({callArgs}).ConfigureAwait(false);"
            );
            // Acknowledge if there's a reply subject
            sb.AppendLine("        if (msg.ReplyTo is not null)");
            sb.AppendLine("        {");
            sb.AppendLine(
                "            await msg.ReplyAsync(Array.Empty<byte>()).ConfigureAwait(false);"
            );
            sb.AppendLine("        }");
        }
        else
        {
            var innerType = ExtractTaskInnerType(method.ReturnType);
            sb.AppendLine(
                $"        var result = await _implementation.{method.Name}({callArgs}).ConfigureAwait(false);"
            );
            sb.AppendLine(
                $"        var responsePayload = MessagePackSerializer.Serialize(result, _options);"
            );
            sb.AppendLine("        if (msg.ReplyTo is not null)");
            sb.AppendLine("        {");
            sb.AppendLine(
                "            await msg.ReplyAsync(responsePayload).ConfigureAwait(false);"
            );
            sb.AppendLine("        }");
        }

        sb.AppendLine("    }");
    }

    private static string ExtractTaskInnerType(string returnType)
    {
        var idx = returnType.IndexOf('<');
        if (idx < 0)
            return returnType;
        return returnType.Substring(idx + 1, returnType.Length - idx - 2);
    }
}
