using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Engine.Generators;

[Generator]
public sealed class Generator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all classes decorated with [Generate]
        var classes = context
            .SyntaxProvider.ForAttributeWithMetadataName(
                "Engine.Core.GenerateAttribute",
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetClassInfo(ctx)
            )
            .Where(static info => info is not null)!;

        context.RegisterSourceOutput(
            classes,
            static (ctx, classInfo) =>
            {
                var source = GenerateSource(classInfo!);
                ctx.AddSource($"{classInfo!.ClassName}.g.cs", source);
            }
        );
    }

    private static ClassInfo? GetClassInfo(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol is not INamedTypeSymbol namedType)
            return null;

        return new ClassInfo(namedType.ContainingNamespace.ToDisplayString(), namedType.Name);
    }

    private static string GenerateSource(ClassInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine($"namespace {info.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"partial class {info.ClassName}");
        sb.AppendLine("{");
        sb.AppendLine($"    // TODO: Add generated members for {info.ClassName}");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private sealed class ClassInfo
    {
        public string Namespace { get; }
        public string ClassName { get; }

        public ClassInfo(string @namespace, string className)
        {
            Namespace = @namespace;
            ClassName = className;
        }
    }
}
